#include "elements/behaviour/call_node.h"

#include <QGraphicsSceneHoverEvent>
#include <QObject>
#include <QPainter>

#include "elements/behaviour/call_capability.h"
#include "elements/behaviour/component_overlay.h"
#include "elements/port.h"
#include "elements/transition.h"
#include "save_info.h"
#include "system/behaviour_canvas.h"
#include "types.h"

namespace
{
QString autoCallTitle(const QString& mode, const QString& capabilityTitle)
{
  if (capabilityTitle.isEmpty())
    return QObject::tr("Call");

  const QString prefix =
      mode == call_capability::kModeAsync ? QObject::tr("Async Call") : QObject::tr("Sync Call");
  return QObject::tr("%1 to %2").arg(prefix, capabilityTitle);
}
}  // namespace

CallNode::CallNode(const QString& id,
                   std::shared_ptr<NodeSaveInfo> info,
                   const QPointF& initialPosition,
                   std::shared_ptr<NodeConfig> nodeConfig,
                   QGraphicsItem* parent)
    // Clone config so Sync/Async/unset SVG swaps do not mutate the shared library entry.
    : BehaviourNode(id, info, initialPosition, std::make_shared<NodeConfig>(*nodeConfig), parent)
{
  setAcceptHoverEvents(true);
  syncNodeSvgFromState();
  syncAbortPortFromMode();
  syncCallLabels();
}

void CallNode::setProperty(const QString& key, QVariant value)
{
  BehaviourNode::setProperty(key, value);

  if (key == call_capability::kModeProperty || key == call_capability::kCapabilityProperty)
  {
    syncNodeSvgFromState();
    if (key == call_capability::kModeProperty)
      syncAbortPortFromMode();
    syncCallLabels();
    if (key == call_capability::kCapabilityProperty && hasCapabilitySelected())
      setHoverTarget(HoverTarget::None);
  }
}

void CallNode::paint(QPainter* painter, const QStyleOptionGraphicsItem* style, QWidget* widget)
{
  applyNodeSvg(call_capability::nodeSvgForState(*this));
  BehaviourNode::paint(painter, style, widget);
}

bool CallNode::hasCapabilitySelected() const
{
  return call_capability::hasCapabilitySelected(*this);
}

qreal CallNode::capabilitySlotDiameter() const
{
  const QRectF drawingBounds = drawingRect(nodeRect());
  return qMin(drawingBounds.width(), drawingBounds.height()) * config()->body.iconScale
         * behaviour::kComponentOverlayDiameterFactor;
}

QRectF CallNode::capabilitySlotSceneRect() const
{
  const QRectF drawingBounds = drawingRect(nodeRect());
  const qreal diameter = capabilitySlotDiameter();
  const qreal radius = diameter * 0.5;
  const QPointF localCenter = behaviour::callCapabilityIconCenter(drawingBounds, diameter, false, true);
  const QPointF center = mapToScene(localCenter);
  return QRectF(center.x() - radius, center.y() - radius, diameter, diameter);
}

bool CallNode::capabilitySlotContainsScenePoint(const QPointF& scenePos) const
{
  // Only the circular capability icon opens the config popup; the rest of the node stays selectable.
  const QRectF r = capabilitySlotSceneRect();
  if (r.isEmpty())
    return false;
  const QPointF d = scenePos - r.center();
  const qreal rr = r.width() * 0.5;
  return (d.x() * d.x() + d.y() * d.y()) <= rr * rr;
}

QString CallNode::chipLabel() const
{
  if (!hasCapabilitySelected())
    return {};

  const QString eventName = call_capability::currentEventName(*this);
  return eventName.isEmpty() ? QObject::tr("Select event") : eventName;
}

QRectF CallNode::eventChipLocalRect() const
{
  if (!hasCapabilitySelected())
    return {};

  const QRectF drawingBounds = drawingRect(nodeRect());
  return behaviour::callEventChipLocalRect(drawingBounds, capabilitySlotDiameter(), chipLabel());
}

QRectF CallNode::eventChipSceneRect() const
{
  const QRectF local = eventChipLocalRect();
  if (local.isEmpty())
    return {};
  return mapRectToScene(local);
}

bool CallNode::eventChipContainsScenePoint(const QPointF& scenePos) const
{
  const QRectF local = eventChipLocalRect();
  if (local.isEmpty())
    return false;
  return mapRectToScene(local.adjusted(-4.0, -4.0, 4.0, 4.0)).contains(scenePos);
}

void CallNode::assignCapability(const QString& capabilityName, const QString& capabilityId, SaveInfo* storage)
{
  // setProperty side effects sync SVG, abort port, and auto-title.
  call_capability::applyCapabilitySelection(*this, capabilityName, capabilityId, storage);
}

void CallNode::syncNodeSvgFromState()
{
  setNodeSvg(call_capability::nodeSvgForState(*this));
}

void CallNode::syncAbortPortFromMode()
{
  if (!mAbortPort)
    return;

  const QString mode = getProperty(call_capability::kModeProperty).toString();
  const bool showAbort = mode == call_capability::kModeAsync;
  if (mAbortPort->isVisible() == showAbort)
  {
    updatePortPositions();
    return;
  }

  mAbortPort->setVisible(showAbort);
  if (!showAbort)
    removeOutgoingAbortTransitions();
  updatePortPositions();
}

void CallNode::syncCallLabels()
{
  syncAutoGeneratedName(autoCallTitle(getProperty(call_capability::kModeProperty).toString(),
                                      call_capability::capabilityName(*this)));
}

void CallNode::removeOutgoingAbortTransitions()
{
  auto* canvas = dynamic_cast<BehaviourCanvas*>(scene());
  if (!canvas)
    return;

  QVector<TransitionItem*> toRemove;
  for (QGraphicsItem* item : canvas->items())
  {
    if (!item || item->type() != Types::TRANSITION)
      continue;

    auto* transition = static_cast<TransitionItem*>(item);
    if (transition->source() != this)
      continue;
    if (transition->getEvent().compare(QStringLiteral("on abort"), Qt::CaseInsensitive) != 0)
      continue;
    toRemove.append(transition);
  }

  for (TransitionItem* transition : toRemove)
  {
    canvas->removeTransition(transition);
    canvas->removeItem(transition);
    delete transition;
  }
}

void CallNode::setHoverTarget(HoverTarget target)
{
  if (mHoverTarget == target)
    return;

  mHoverTarget = target;
  behaviour::setSceneViewCursor(this, target != HoverTarget::None);

  if (target == HoverTarget::EmptySlot)
    setToolTip(QObject::tr("Add capability"));
  else if (target == HoverTarget::EventChip || target == HoverTarget::CapabilityIcon)
    setToolTip(QObject::tr("Select capability and event"));
  else
    setToolTip(QString());

  update();
}

void CallNode::hoverMoveEvent(QGraphicsSceneHoverEvent* event)
{
  if (!hasCapabilitySelected() && capabilitySlotContainsScenePoint(event->scenePos()))
    setHoverTarget(HoverTarget::EmptySlot);
  else if (eventChipContainsScenePoint(event->scenePos()))
    setHoverTarget(HoverTarget::EventChip);
  else if (hasCapabilitySelected() && capabilitySlotContainsScenePoint(event->scenePos()))
    setHoverTarget(HoverTarget::CapabilityIcon);
  else
    setHoverTarget(HoverTarget::None);
  QGraphicsItem::hoverMoveEvent(event);
}

void CallNode::hoverLeaveEvent(QGraphicsSceneHoverEvent* event)
{
  setHoverTarget(HoverTarget::None);
  NodeItem::hoverLeaveEvent(event);
}

void CallNode::paintBehaviourExtras(QPainter* painter, const QStyleOptionGraphicsItem* style, QWidget* widget)
{
  Q_UNUSED(style);
  Q_UNUSED(widget);

  if (hasCapabilitySelected())
  {
    behaviour::paintSelectedComponentOverlay(this, painter);
    behaviour::paintCallEventChip(painter,
                                  drawingRect(nodeRect()),
                                  capabilitySlotDiameter(),
                                  chipLabel(),
                                  mHoverTarget == HoverTarget::EventChip);
    return;
  }

  const QRectF drawingBounds = drawingRect(nodeRect());
  const qreal diameter = capabilitySlotDiameter();
  const QPointF center = behaviour::callCapabilityIconCenter(drawingBounds, diameter, false, true);
  behaviour::paintEmptySlotSvg(painter, center, diameter, mHoverTarget == HoverTarget::EmptySlot);
}
