#include "elements/behaviour/call_node.h"

#include <QGraphicsSceneHoverEvent>
#include <QObject>
#include <QPainter>
#include <QPolygonF>

#include "app_configs.h"
#include "elements/behaviour/call_capability.h"
#include "elements/behaviour/component_overlay.h"
#include "elements/port.h"
#include "elements/transition.h"
#include "keys.h"
#include "save_info.h"
#include "system/behaviour_canvas.h"
#include "types.h"

namespace
{
QString autoCallTitle(const QString& mode, const QString& capabilityTitle)
{
  const QString prefix =
      mode == call_capability::kModeAsync ? QObject::tr("Async Call") : QObject::tr("Sync Call");
  if (capabilityTitle.isEmpty())
    return prefix;
  return QObject::tr("%1 to %2").arg(prefix, capabilityTitle);
}
}  // namespace

CallNode::CallNode(const QString& id,
                   std::shared_ptr<NodeSaveInfo> info,
                   const QPointF& initialPosition,
                   std::shared_ptr<NodeConfig> nodeConfig,
                   QGraphicsItem* parent)
    // Clone config so Sync/Async/unset SVG swaps do not mutate the shared library entry.
    : BehaviourNode(id, info, initialPosition, std::make_shared<NodeConfig>(*nodeConfig), parent)
{
  setAcceptHoverEvents(true);
  syncNodeSvgFromState();
  syncAbortPortFromMode();
  syncCallLabels();
}

void CallNode::setProperty(const QString& key, QVariant value)
{
  BehaviourNode::setProperty(key, value);

  if (key == call_capability::kModeProperty || key == call_capability::kCapabilityProperty)
  {
    syncNodeSvgFromState();
    if (key == call_capability::kModeProperty)
      syncAbortPortFromMode();
    syncCallLabels();
    if (key == call_capability::kCapabilityProperty && hasCapabilitySelected())
      setEmptySlotHovered(false);
  }
}

void CallNode::paint(QPainter* painter, const QStyleOptionGraphicsItem* style, QWidget* widget)
{
  applyNodeSvg(call_capability::nodeSvgForState(*this));
  BehaviourNode::paint(painter, style, widget);
}

bool CallNode::hasCapabilitySelected() const
{
  return call_capability::hasCapabilitySelected(*this);
}

qreal CallNode::capabilitySlotDiameter() const
{
  const QRectF drawingBounds = drawingRect(nodeRect());
  return qMin(drawingBounds.width(), drawingBounds.height()) * config()->body.iconScale
         * behaviour::kComponentOverlayDiameterFactor;
}

QRectF CallNode::capabilitySlotSceneRect() const
{
  const QRectF drawingBounds = drawingRect(nodeRect());
  const qreal diameter = capabilitySlotDiameter();
  const qreal radius = diameter * 0.5;
  const bool hasEvent = !call_capability::currentEventName(*this).isEmpty();
  const bool capabilitySelected = hasCapabilitySelected();
  const QPointF localCenter = behaviour::callCapabilityIconCenter(
      drawingBounds, diameter, hasEvent, capabilitySelected, !capabilitySelected);
  const QPointF center = mapToScene(localCenter);
  return QRectF(center.x() - radius, center.y() - radius, diameter, diameter);
}

bool CallNode::capabilitySlotContainsScenePoint(const QPointF& scenePos) const
{
  // Only the circular capability icon opens the config popup; the rest of the node stays selectable.
  const QRectF r = capabilitySlotSceneRect();
  if (r.isEmpty())
    return false;
  const QPointF d = scenePos - r.center();
  const qreal rr = r.width() * 0.5;
  return (d.x() * d.x() + d.y() * d.y()) <= rr * rr;
}

QRectF CallNode::eventChipLocalRect() const
{
  if (!hasCapabilitySelected())
    return {};

  const QRectF drawingBounds = drawingRect(nodeRect());
  const qreal diameter = capabilitySlotDiameter();
  const bool hasEvent = !call_capability::currentEventName(*this).isEmpty();
  return behaviour::callEventChipLocalRect(drawingBounds, diameter, hasEvent);
}

QRectF CallNode::eventChipSceneRect() const
{
  const QRectF local = eventChipLocalRect();
  if (local.isEmpty())
    return {};
  return mapRectToScene(local);
}

bool CallNode::eventChipContainsScenePoint(const QPointF& scenePos) const
{
  const QRectF local = eventChipLocalRect();
  if (local.isEmpty())
    return false;
  return mapRectToScene(local.adjusted(-4.0, -4.0, 4.0, 4.0)).contains(scenePos);
}

void CallNode::assignCapability(const QString& capabilityName, const QString& capabilityId, SaveInfo* storage)
{
  // setProperty side effects sync SVG, abort port, and auto-title.
  call_capability::applyCapabilitySelection(*this, capabilityName, capabilityId, storage);
}

void CallNode::syncNodeSvgFromState()
{
  setNodeSvg(call_capability::nodeSvgForState(*this));
}

void CallNode::syncAbortPortFromMode()
{
  if (!mAbortPort)
    return;

  const QString mode = getProperty(call_capability::kModeProperty).toString();
  const bool showAbort = mode == call_capability::kModeAsync;
  if (mAbortPort->isVisible() == showAbort)
  {
    updatePortPositions();
    return;
  }

  mAbortPort->setVisible(showAbort);
  if (!showAbort)
    removeOutgoingAbortTransitions();
  updatePortPositions();
}

void CallNode::syncCallLabels()
{
  const QVariant wasAutoGenerated = getProperty(QStringLiteral("name_auto_generated"));
  if (wasAutoGenerated.isValid() && !wasAutoGenerated.toBool())
  {
    update();
    return;
  }

  const QString mode = getProperty(call_capability::kModeProperty).toString();
  const QString title = autoCallTitle(mode, call_capability::capabilityName(*this));
  if (getProperty(ConfigKeys::NAME).toString() != title)
    BehaviourNode::setProperty(ConfigKeys::NAME, title);
  else
    update();
}

void CallNode::removeOutgoingAbortTransitions()
{
  auto* canvas = dynamic_cast<BehaviourCanvas*>(scene());
  if (!canvas)
    return;

  QVector<TransitionItem*> toRemove;
  for (QGraphicsItem* item : canvas->items())
  {
    if (!item || item->type() != Types::TRANSITION)
      continue;

    auto* transition = static_cast<TransitionItem*>(item);
    if (transition->source() != this)
      continue;
    if (transition->getEvent().compare(QStringLiteral("on abort"), Qt::CaseInsensitive) != 0)
      continue;
    toRemove.append(transition);
  }

  for (TransitionItem* transition : toRemove)
  {
    canvas->removeTransition(transition);
    canvas->removeItem(transition);
    delete transition;
  }
}

void CallNode::paintEventChip(QPainter* painter) const
{
  const QRectF chip = eventChipLocalRect();
  if (chip.isEmpty() || !painter)
    return;

  painter->setRenderHint(QPainter::Antialiasing, true);
  painter->setPen(Qt::NoPen);
  painter->setBrush(QBrush(Config::FOREGROUND));

  const QPointF c = chip.center();
  const qreal w = chip.width() * 0.55;
  const qreal h = chip.height() * 0.35;
  QPolygonF triangle;
  triangle << QPointF(c.x() - w * 0.5, c.y() - h * 0.35)
           << QPointF(c.x() + w * 0.5, c.y() - h * 0.35)
           << QPointF(c.x(), c.y() + h * 0.65);
  painter->drawPolygon(triangle);
}

void CallNode::setEmptySlotHovered(bool hovered)
{
  behaviour::applyAddCapabilityHover(this, mEmptySlotHovered, hovered);
}

void CallNode::hoverMoveEvent(QGraphicsSceneHoverEvent* event)
{
  setEmptySlotHovered(!hasCapabilitySelected() && capabilitySlotContainsScenePoint(event->scenePos()));
  QGraphicsItem::hoverMoveEvent(event);
}

void CallNode::hoverLeaveEvent(QGraphicsSceneHoverEvent* event)
{
  setEmptySlotHovered(false);
  NodeItem::hoverLeaveEvent(event);
}

void CallNode::paintBehaviourExtras(QPainter* painter, const QStyleOptionGraphicsItem* style, QWidget* widget)
{
  Q_UNUSED(style);
  Q_UNUSED(widget);

  if (hasCapabilitySelected())
  {
    behaviour::paintSelectedComponentOverlay(this, painter);
    paintEventChip(painter);
    return;
  }

  const QRectF drawingBounds = drawingRect(nodeRect());
  const qreal diameter = capabilitySlotDiameter();
  const QPointF center =
      behaviour::callCapabilityIconCenter(drawingBounds, diameter, false, false, /*offsetPastArrow=*/true);
  behaviour::paintEmptySlotSvg(painter, center, diameter, mEmptySlotHovered);
}
