#include "elements/behaviour/call_capability.h"

#include <QJsonArray>
#include <QJsonObject>

#include "elements/node.h"
#include "keys.h"
#include "save_info.h"

namespace call_capability
{
namespace
{
void maybeSetAutoName(NodeItem& node, const QString& name)
{
  const auto wasAutoGenerated = node.getProperty(QStringLiteral("name_auto_generated"));
  if (!wasAutoGenerated.isValid() || wasAutoGenerated.toBool())
    node.setProperty(ConfigKeys::NAME, name);
}

void writeCapabilityData(NodeItem& node, const QString& capabilityName, const QJsonArray& options)
{
  QJsonObject object;
  const QVariant existing = node.getProperty(kCapabilityProperty);
  if (existing.isValid())
    object = existing.toJsonObject();
  object[ConfigKeys::DATA] = capabilityName;
  object[ConfigKeys::OPTIONS] = options;
  node.setProperty(kCapabilityProperty, object);
}
}  // namespace

bool isCallNodeType(const QString& nodeType)
{
  return nodeType == QStringLiteral("Koda::Call");
}

bool hasCapabilitySelected(const NodeItem& node)
{
  const QVariant propertyValue = node.getProperty(kCapabilityProperty);
  if (!propertyValue.isValid())
    return false;

  const QJsonObject object = propertyValue.toJsonObject();
  const QString data = object.value(ConfigKeys::DATA).toString().trimmed();
  return !data.isEmpty() && data != QStringLiteral("-");
}

bool canAsync(const SaveInfo& storage, const QString& capabilityId)
{
  return !storage.getEventsOfTypeFromNode(capabilityId, {Types::CallType::TRIGGER}).isEmpty();
}

bool canSync(const SaveInfo& storage, const QString& capabilityId)
{
  return !storage
              .getEventsOfTypeFromNode(capabilityId,
                                       {Types::CallType::TRIGGER, Types::CallType::ABORT, Types::CallType::IN})
              .isEmpty();
}

QString defaultMode(const SaveInfo& storage, const QString& capabilityId)
{
  return canAsync(storage, capabilityId) ? kModeAsync : kModeSync;
}

QList<Types::CallType> eventTypesForMode(const QString& mode)
{
  if (mode == kModeAsync)
    return {Types::CallType::TRIGGER};
  return {Types::CallType::TRIGGER, Types::CallType::ABORT, Types::CallType::IN};
}

QString nodeSvgForState(const NodeItem& node)
{
  if (!hasCapabilitySelected(node))
    return kNodeSvgUnset;
  return node.getProperty(kModeProperty).toString() == kModeAsync ? kNodeSvgAsync : kNodeSvgSync;
}

void applyCapabilitySelection(NodeItem& node,
                              const QString& capabilityName,
                              const QString& capabilityId,
                              SaveInfo* storage)
{
  if (capabilityName.isEmpty() || capabilityId.isEmpty())
    return;

  writeCapabilityData(node, capabilityName, QJsonArray());

  if (!storage)
    return;

  QString mode = defaultMode(*storage, capabilityId);
  if (mode == kModeSync && !canSync(*storage, capabilityId) && canAsync(*storage, capabilityId))
    mode = kModeAsync;
  if (mode == kModeAsync && !canAsync(*storage, capabilityId))
    mode = kModeSync;
  node.setProperty(kModeProperty, mode);

  const auto events = storage->getEventsOfTypeFromNode(capabilityId, eventTypesForMode(mode));
  if (events.isEmpty())
  {
    maybeSetAutoName(node, capabilityName);
    return;
  }

  QJsonArray options;
  QJsonObject eventItem;
  eventItem[ConfigKeys::DATA] = events.first()->getname();
  eventItem[ConfigKeys::TYPE] = Types::PropertyTypesToString(Types::PropertyTypes::EVENT_SELECT);
  eventItem[ConfigKeys::IS_VARIABLE] = false;
  while (options.size() <= kEventIndex)
    options.append(QJsonObject());
  options[kEventIndex] = eventItem;
  writeCapabilityData(node, capabilityName, options);
  maybeSetAutoName(node, capabilityName + QLatin1Char(' ') + events.first()->getname());
}
}  // namespace call_capability
