#include "elements/behaviour/link_out_node.h"

#include <QGraphicsSceneMouseEvent>
#include <QObject>

#include "keys.h"
#include "system/canvas.h"

namespace
{
QString autoLinkOutTitle(const QString& targetName)
{
  if (targetName.isEmpty())
    return QObject::tr("Link out");
  return QObject::tr("Link-out to %1").arg(targetName);
}
}  // namespace

LinkOutNode::LinkOutNode(const QString& id,
                         std::shared_ptr<NodeSaveInfo> info,
                         const QPointF& initialPosition,
                         std::shared_ptr<NodeConfig> nodeConfig,
                         QGraphicsItem* parent)
    : BehaviourNode(id, info, initialPosition, nodeConfig, parent)
{
  syncLinkOutLabel();
}

void LinkOutNode::setProperty(const QString& key, QVariant value)
{
  BehaviourNode::setProperty(key, value);
  if (key == link_nodes::kTargetPropertyId)
    syncLinkOutLabel();
}

QString LinkOutNode::targetId() const
{
  const QVariant value = getProperty(link_nodes::kTargetPropertyId);
  if (!value.isValid())
    return {};
  return value.toString().trimmed();
}

QString LinkOutNode::targetName() const
{
  const QString id = targetId();
  if (id.isEmpty() || !scene())
    return {};

  for (QGraphicsItem* item : scene()->items())
  {
    if (!item || item->type() != NodeItem::Type)
      continue;
    auto* candidate = static_cast<NodeItem*>(item);
    if (candidate->id() == id)
      return candidate->nodeName();
  }

  return {};
}

void LinkOutNode::syncLinkOutLabel()
{
  const QVariant wasAutoGenerated = getProperty(QStringLiteral("name_auto_generated"));
  if (wasAutoGenerated.isValid() && !wasAutoGenerated.toBool())
  {
    update();
    return;
  }

  const QString title = autoLinkOutTitle(targetName());
  if (getProperty(ConfigKeys::NAME).toString() != title)
    BehaviourNode::setProperty(ConfigKeys::NAME, title);
  else
    update();
}

QVariant LinkOutNode::itemChange(GraphicsItemChange change, const QVariant& value)
{
  if (change == QGraphicsItem::ItemSceneHasChanged && scene())
    syncLinkOutLabel();
  return BehaviourNode::itemChange(change, value);
}

void LinkOutNode::mouseDoubleClickEvent(QGraphicsSceneMouseEvent* event)
{
  if (event->button() == Qt::LeftButton && labelContainsScenePoint(event->scenePos()))
  {
    NodeItem::mouseDoubleClickEvent(event);
    return;
  }

  if (event->button() == Qt::LeftButton)
  {
    const QString id = targetId();
    if (!id.isEmpty())
    {
      if (auto* canvas = dynamic_cast<Canvas*>(scene()))
        canvas->onFocusNode(QString(), id);
    }
  }

  QGraphicsItem::mouseDoubleClickEvent(event);
}
