#include "elements/behaviour/link_out_node.h"

#include <QGraphicsSceneHoverEvent>
#include <QGraphicsSceneMouseEvent>
#include <QObject>
#include <QPainter>
#include <algorithm>

#include "elements/behaviour/component_overlay.h"
#include "system/canvas.h"

namespace
{
constexpr qreal kChevronHitPad = 8.0;

QString autoLinkOutTitle(const QString& targetName)
{
  if (targetName.isEmpty())
    return QObject::tr("Link out");
  return QObject::tr("Link-out to %1").arg(targetName);
}

/** True when @p linkIn sits in this container or an enclosing flow of @p linkOut. */
bool canReachLinkIn(const NodeItem* linkOut, const NodeItem* linkIn)
{
  if (!linkOut || !linkIn)
    return false;

  NodeItem* inParent = linkIn->parentNode();
  for (NodeItem* container = linkOut->parentNode();;)
  {
    if (container == inParent)
      return true;
    if (!container)
      return false;
    NodeItem* host = container->subflowHost();
    container = host ? host->parentNode() : container->parentNode();
  }
}
}  // namespace

LinkOutNode::LinkOutNode(const QString& id,
                         std::shared_ptr<NodeSaveInfo> info,
                         const QPointF& initialPosition,
                         std::shared_ptr<NodeConfig> nodeConfig,
                         QGraphicsItem* parent)
    : BehaviourNode(id, info, initialPosition, nodeConfig, parent)
{
  setAcceptHoverEvents(true);
  syncLinkOutLabel();
}

void LinkOutNode::setProperty(const QString& key, QVariant value)
{
  BehaviourNode::setProperty(key, value);
  if (key == link_nodes::kTargetPropertyId)
    syncLinkOutLabel();
}

QString LinkOutNode::targetId() const
{
  const QVariant value = getProperty(link_nodes::kTargetPropertyId);
  if (!value.isValid())
    return {};
  return value.toString().trimmed();
}

QString LinkOutNode::targetName() const
{
  const QString id = targetId();
  if (id.isEmpty() || !scene())
    return {};

  for (QGraphicsItem* item : scene()->items())
  {
    if (!item || item->type() != NodeItem::Type)
      continue;
    auto* candidate = static_cast<NodeItem*>(item);
    if (candidate->id() == id)
      return candidate->nodeName();
  }

  return {};
}

QVector<LinkOutNode::LinkInTarget> LinkOutNode::linkInTargets() const
{
  QVector<LinkInTarget> targets;
  if (!scene())
    return targets;

  for (QGraphicsItem* item : scene()->items())
  {
    if (!item || item == this || item->type() != NodeItem::Type)
      continue;

    auto* candidate = static_cast<NodeItem*>(item);
    if (candidate->nodeType() != link_nodes::kLinkInType)
      continue;
    if (!canReachLinkIn(this, candidate))
      continue;

    QString name = candidate->nodeName().trimmed();
    if (name.isEmpty())
      name = QObject::tr("Link in");
    targets.push_back({candidate->id(), name});
  }

  std::sort(targets.begin(), targets.end(),
            [](const LinkInTarget& a, const LinkInTarget& b) { return a.name.localeAwareCompare(b.name) < 0; });
  return targets;
}

void LinkOutNode::assignTarget(const QString& linkInId)
{
  setProperty(link_nodes::kTargetPropertyId, linkInId);
}

QRectF LinkOutNode::chevronLocalRect() const
{
  return behaviour::linkOutChevronLocalRect(drawingRect(nodeRect()));
}

QRectF LinkOutNode::chevronSceneRect() const
{
  return mapRectToScene(chevronLocalRect());
}

bool LinkOutNode::chevronContainsScenePoint(const QPointF& scenePos) const
{
  const QRectF r = chevronSceneRect();
  if (!r.isValid() || r.isEmpty())
    return false;
  return r.adjusted(-kChevronHitPad, -kChevronHitPad, kChevronHitPad, kChevronHitPad).contains(scenePos);
}

void LinkOutNode::setChevronHovered(bool hovered)
{
  if (mChevronHovered == hovered)
    return;

  mChevronHovered = hovered;
  behaviour::setSceneViewCursor(this, hovered);

  if (hovered)
  {
    const QString name = targetName();
    setToolTip(name.isEmpty() ? QObject::tr("Select Link in") : name);
  }
  else
  {
    setToolTip(QString());
  }
  update();
}

void LinkOutNode::hoverMoveEvent(QGraphicsSceneHoverEvent* event)
{
  setChevronHovered(chevronContainsScenePoint(event->scenePos()));
  QGraphicsItem::hoverMoveEvent(event);
}

void LinkOutNode::hoverLeaveEvent(QGraphicsSceneHoverEvent* event)
{
  setChevronHovered(false);
  NodeItem::hoverLeaveEvent(event);
}

void LinkOutNode::paintBehaviourExtras(QPainter* painter, const QStyleOptionGraphicsItem* style, QWidget* widget)
{
  Q_UNUSED(style);
  Q_UNUSED(widget);
  if (!painter)
    return;

  behaviour::paintLinkOutChevron(painter, drawingRect(nodeRect()), mChevronHovered);
}

void LinkOutNode::syncLinkOutLabel()
{
  syncAutoGeneratedName(autoLinkOutTitle(targetName()));
}

QVariant LinkOutNode::itemChange(GraphicsItemChange change, const QVariant& value)
{
  if (change == QGraphicsItem::ItemSceneHasChanged && scene())
    syncLinkOutLabel();
  return BehaviourNode::itemChange(change, value);
}

void LinkOutNode::mouseDoubleClickEvent(QGraphicsSceneMouseEvent* event)
{
  if (event->button() == Qt::LeftButton && labelContainsScenePoint(event->scenePos()))
  {
    NodeItem::mouseDoubleClickEvent(event);
    return;
  }

  if (event->button() == Qt::LeftButton && chevronContainsScenePoint(event->scenePos()))
  {
    event->accept();
    return;
  }

  if (event->button() == Qt::LeftButton)
  {
    const QString id = targetId();
    if (!id.isEmpty())
    {
      if (auto* canvas = dynamic_cast<Canvas*>(scene()))
        canvas->onFocusNode(QString(), id);
    }
  }

  QGraphicsItem::mouseDoubleClickEvent(event);
}
