#include "elements/behaviour/wait_node.h"

#include <QGraphicsSceneHoverEvent>
#include <QObject>
#include <QPainter>
#include <QSvgRenderer>

#include "elements/behaviour/call_capability.h"
#include "elements/behaviour/component_overlay.h"
#include "elements/transition.h"
#include "style_helpers.h"
#include "system/behaviour_canvas.h"
#include "types.h"

namespace
{
constexpr qreal kChipHitPad = 8.0;

QString autoWaitTitle(const QString& capabilityTitle)
{
  if (capabilityTitle.isEmpty())
    return QObject::tr("Wait for signal");
  return QObject::tr("Wait for %1").arg(capabilityTitle);
}

QSvgRenderer& sharedWaitIconRenderer()
{
  static QSvgRenderer renderer(iconPathFromTheme(behaviour::kWaitIconSvg));
  return renderer;
}

void paintWaitIcon(QPainter* painter, const QRectF& drawingBounds, qreal diameter)
{
  if (!painter || diameter <= 0.0)
    return;

  QSvgRenderer& renderer = sharedWaitIconRenderer();
  if (!renderer.isValid())
    return;

  const QRectF target = behaviour::waitPauseLocalRect(drawingBounds, diameter);
  if (target.isEmpty())
    return;
  painter->setRenderHint(QPainter::Antialiasing, true);
  renderer.render(painter, target);
}
}  // namespace

WaitNode::WaitNode(const QString& id,
                   std::shared_ptr<NodeSaveInfo> info,
                   const QPointF& initialPosition,
                   std::shared_ptr<NodeConfig> nodeConfig,
                   QGraphicsItem* parent)
    // Clone config so the palette keeps node_wait.svg while the canvas uses the middle shape.
    : BehaviourNode(id, info, initialPosition, std::make_shared<NodeConfig>(*nodeConfig), parent)
{
  setAcceptHoverEvents(true);
  setNodeSvg(behaviour::kWaitCanvasNodeSvg);
  syncWaitLabels();
}

void WaitNode::setProperty(const QString& key, QVariant value)
{
  const QString previousCapability =
      (key == call_capability::kCapabilityProperty) ? call_capability::capabilityName(*this) : QString();

  BehaviourNode::setProperty(key, value);

  if (key != call_capability::kCapabilityProperty)
    return;

  if (previousCapability != call_capability::capabilityName(*this))
    clearOutgoingSignalEvents();
  syncWaitLabels();
  if (hasCapabilitySelected())
    setHoverTarget(HoverTarget::None);
}

bool WaitNode::hasCapabilitySelected() const
{
  return call_capability::hasCapabilitySelected(*this);
}

qreal WaitNode::waitIconDiameter() const
{
  const QRectF drawingBounds = drawingRect(nodeRect());
  return qMin(drawingBounds.width(), drawingBounds.height()) * config()->body.iconScale
         * behaviour::kWaitComponentOverlayDiameterFactor;
}

QRectF WaitNode::chipLocalRect() const
{
  return behaviour::waitCapabilityChipLocalRect(drawingRect(nodeRect()), waitIconDiameter());
}

QRectF WaitNode::waitChipSceneRect() const
{
  return mapRectToScene(chipLocalRect());
}

bool WaitNode::waitChipContainsScenePoint(const QPointF& scenePos) const
{
  const QRectF r = waitChipSceneRect();
  if (!r.isValid() || r.isEmpty())
    return false;
  return r.adjusted(-kChipHitPad, -kChipHitPad, kChipHitPad, kChipHitPad).contains(scenePos);
}

void WaitNode::assignCapability(const QString& capabilityName)
{
  call_capability::applyCapabilitySelectionNameOnly(*this, capabilityName);
}

void WaitNode::syncWaitLabels()
{
  syncAutoGeneratedName(autoWaitTitle(call_capability::capabilityName(*this)));
}

void WaitNode::clearOutgoingSignalEvents()
{
  auto* canvas = dynamic_cast<BehaviourCanvas*>(scene());
  if (!canvas)
    return;

  for (QGraphicsItem* item : canvas->items())
  {
    if (!item || item->type() != Types::TRANSITION)
      continue;

    auto* transition = static_cast<TransitionItem*>(item);
    if (transition->source() != this)
      continue;
    if (transition->getEvent().isEmpty() && transition->getName().isEmpty())
      continue;

    transition->setEvent(QString());
    transition->setName(QString());
    transition->updatePath();
  }
}

void WaitNode::setHoverTarget(HoverTarget target)
{
  if (mHoverTarget == target)
    return;

  mHoverTarget = target;
  behaviour::setSceneViewCursor(this, target == HoverTarget::Chip);

  QString tooltip;
  if (target == HoverTarget::Chip)
  {
    const QString name = call_capability::capabilityName(*this);
    tooltip = name.isEmpty() ? QObject::tr("Select capability") : name;
  }
  setToolTip(tooltip);
  update();
}

void WaitNode::hoverMoveEvent(QGraphicsSceneHoverEvent* event)
{
  setHoverTarget(waitChipContainsScenePoint(event->scenePos()) ? HoverTarget::Chip : HoverTarget::None);
  QGraphicsItem::hoverMoveEvent(event);
}

void WaitNode::hoverLeaveEvent(QGraphicsSceneHoverEvent* event)
{
  setHoverTarget(HoverTarget::None);
  NodeItem::hoverLeaveEvent(event);
}

void WaitNode::paintBehaviourExtras(QPainter* painter, const QStyleOptionGraphicsItem* style, QWidget* widget)
{
  Q_UNUSED(style);
  Q_UNUSED(widget);
  if (!painter)
    return;

  const QRectF drawingBounds = drawingRect(nodeRect());
  const qreal diameter = waitIconDiameter();
  paintWaitIcon(painter, drawingBounds, diameter);
  behaviour::paintWaitCapabilityChip(this, painter, drawingBounds, diameter, mHoverTarget == HoverTarget::Chip);
}
