#include "elements/behaviour/wait_node.h"

#include <QGraphicsSceneHoverEvent>
#include <QObject>
#include <QPainter>

#include "elements/behaviour/call_capability.h"
#include "elements/behaviour/component_overlay.h"
#include "elements/transition.h"
#include "keys.h"
#include "system/behaviour_canvas.h"
#include "types.h"

namespace
{
QString autoWaitTitle(const QString& capabilityTitle)
{
  if (capabilityTitle.isEmpty())
    return QObject::tr("Wait for signal");
  return QObject::tr("Wait for %1").arg(capabilityTitle);
}
}  // namespace

WaitNode::WaitNode(const QString& id,
                   std::shared_ptr<NodeSaveInfo> info,
                   const QPointF& initialPosition,
                   std::shared_ptr<NodeConfig> nodeConfig,
                   QGraphicsItem* parent)
    // Clone config so palette keeps node_wait.svg while canvas uses the capability layout SVG.
    : BehaviourNode(id, info, initialPosition, std::make_shared<NodeConfig>(*nodeConfig), parent)
{
  setAcceptHoverEvents(true);
  setNodeSvg(behaviour::kWaitNodeSvgCapability);
  syncWaitLabels();
}

void WaitNode::setProperty(const QString& key, QVariant value)
{
  const QString previousCapability =
      (key == call_capability::kCapabilityProperty) ? call_capability::capabilityName(*this) : QString();

  BehaviourNode::setProperty(key, value);

  if (key != call_capability::kCapabilityProperty)
    return;

  if (previousCapability != call_capability::capabilityName(*this))
    clearOutgoingSignalEvents();
  syncWaitLabels();
  if (hasCapabilitySelected())
    setEmptySlotHovered(false);
}

bool WaitNode::hasCapabilitySelected() const
{
  return call_capability::hasCapabilitySelected(*this);
}

qreal WaitNode::capabilitySlotDiameter() const
{
  const QRectF drawingBounds = drawingRect(nodeRect());
  return qMin(drawingBounds.width(), drawingBounds.height()) * config()->body.iconScale
         * behaviour::kWaitComponentOverlayDiameterFactor;
}

QRectF WaitNode::capabilitySlotSceneRect() const
{
  const QRectF drawingBounds = drawingRect(nodeRect());
  const qreal diameter = capabilitySlotDiameter();
  const qreal radius = diameter * 0.5;
  const QPointF center = mapToScene(behaviour::waitCapabilityIconCenter(drawingBounds));
  return QRectF(center.x() - radius, center.y() - radius, diameter, diameter);
}

bool WaitNode::capabilitySlotContainsScenePoint(const QPointF& scenePos) const
{
  const QRectF r = capabilitySlotSceneRect();
  if (r.isEmpty())
    return false;
  const QPointF d = scenePos - r.center();
  const qreal rr = r.width() * 0.5;
  return (d.x() * d.x() + d.y() * d.y()) <= rr * rr;
}

void WaitNode::assignCapability(const QString& capabilityName)
{
  call_capability::applyCapabilitySelectionNameOnly(*this, capabilityName);
}

void WaitNode::syncWaitLabels()
{
  const QVariant wasAutoGenerated = getProperty(QStringLiteral("name_auto_generated"));
  if (wasAutoGenerated.isValid() && !wasAutoGenerated.toBool())
  {
    update();
    return;
  }

  const QString title = autoWaitTitle(call_capability::capabilityName(*this));
  if (getProperty(ConfigKeys::NAME).toString() != title)
    BehaviourNode::setProperty(ConfigKeys::NAME, title);
  else
    update();
}

void WaitNode::clearOutgoingSignalEvents()
{
  auto* canvas = dynamic_cast<BehaviourCanvas*>(scene());
  if (!canvas)
    return;

  for (QGraphicsItem* item : canvas->items())
  {
    if (!item || item->type() != Types::TRANSITION)
      continue;

    auto* transition = static_cast<TransitionItem*>(item);
    if (transition->source() != this)
      continue;
    if (transition->getEvent().isEmpty() && transition->getName().isEmpty())
      continue;

    transition->setEvent(QString());
    transition->setName(QString());
    transition->updatePath();
  }
}

void WaitNode::setEmptySlotHovered(bool hovered)
{
  behaviour::applyAddCapabilityHover(this, mEmptySlotHovered, hovered);
}

void WaitNode::hoverMoveEvent(QGraphicsSceneHoverEvent* event)
{
  setEmptySlotHovered(!hasCapabilitySelected() && capabilitySlotContainsScenePoint(event->scenePos()));
  QGraphicsItem::hoverMoveEvent(event);
}

void WaitNode::hoverLeaveEvent(QGraphicsSceneHoverEvent* event)
{
  setEmptySlotHovered(false);
  NodeItem::hoverLeaveEvent(event);
}

void WaitNode::paintBehaviourExtras(QPainter* painter, const QStyleOptionGraphicsItem* style, QWidget* widget)
{
  Q_UNUSED(style);
  Q_UNUSED(widget);

  if (hasCapabilitySelected())
  {
    behaviour::paintSelectedComponentOverlay(this, painter);
    return;
  }

  const QRectF drawingBounds = drawingRect(nodeRect());
  behaviour::paintEmptySlotSvg(painter, behaviour::waitCapabilityIconCenter(drawingBounds), capabilitySlotDiameter(),
                               mEmptySlotHovered);
}
