# Dark theme: Nord-ish
background: #2E3440
foreground: #ECEFF4
faded_foreground: #AAB3C2
highlight: #81A1C1
selection_fg: #ECEFF4
selection_bg: #4C566A
border_radius: 8
icon_size: 16
eyedropper_icon: :/icons/eye-dropper-dark.svg

info_color: #5E81AC
error_color: #BF616A
warning_color: #EBCB8B

notification_width: 300
min_notification_height: 56
max_notification_height: 180

scrollbar_handle: #4C566A
scrollbar_handle_hover: #5B6576

button_size: 30

input_bg: #242A35
input_border: #3B4252
input_focus_border: #88C0D0
combobox_bg: #3B4252
control_border: #4C566A

combobox_hover_border: #88C0D0
arrow_icon_up: :/icons/arrow-up-dark.svg
arrow_icon_down: :/icons/arrow-down-dark.svg
arrow_icon_right: :/icons/arrow-right-dark.svg

uncheck_icon: :/icons/uncheck-dark.svg
check_icon: :/icons/check-dark.svg
limit_icon: :/icons/limit-dark.svg

tab_bg: #3B4252
tab_border_color: #4C566A
tab_selected_bg: #2E3440

menu_bg: #2E3440
menu_border: #4C566A

toolbar_bg: #2B313C
toolbar_border: #4C566A
toolbutton_hover_bg: #3B4252