# Dark theme: Monokai
background: #272822
foreground: #F8F8F2
faded_foreground: #CFCFC2
highlight: #A6E22E
selection_fg: #272822
selection_bg: #F8F8F2
border_radius: 8
icon_size: 16

info_color: #66D9EF
error_color: #F92672
warning_color: #FD971F

notification_width: 360
min_notification_height: 56
max_notification_height: 180
notification_left_margin: 16
notification_top_margin: 16
notification_between_margin: 10

scrollbar_handle: #5A5A5A
scrollbar_handle_hover: #6D6D6D

button_size: 30

input_bg: #1F201B
input_border: #3E3D32
input_focus_border: #66D9EF
combobox_bg: #3E3D32
control_border: #5A5A5A

combobox_hover_border: #A6E22E
arrow_icon_up: :/icons/arrow-up-dark.svg
arrow_icon_down: :/icons/arrow-down-dark.svg
arrow_icon_right: :/icons/arrow-right-dark.svg

uncheck_icon: :/icons/uncheck-dark.svg
check_icon: :/icons/check-dark.svg
limit_icon: :/icons/limit-dark.svg

tab_bg: #3E3D32
tab_border_color: #5A5A5A
tab_selected_bg: #272822

menu_bg: #272822
menu_border: #5A5A5A

toolbar_bg: #24251F
toolbar_border: #5A5A5A
toolbutton_hover_bg: #3E3D32