# Dark theme: Tokyo Night
background: #1A1B26
foreground: #C0CAF5
faded_foreground: #9AA5CE
highlight: #7AA2F7
selection_fg: #1A1B26
selection_bg: #C0CAF5
border_radius: 8
icon_size: 16
eyedropper_icon: :/icons/eye-dropper-dark.svg

info_color: #2AC3DE
error_color: #F7768E
warning_color: #E0AF68

notification_width: 300
min_notification_height: 56
max_notification_height: 180

scrollbar_handle: #414868
scrollbar_handle_hover: #565F89

button_size: 30

input_bg: #141520
input_border: #2F334D
input_focus_border: #7AA2F7
combobox_bg: #2F334D
control_border: #414868

combobox_hover_border: #2AC3DE
arrow_icon_up: :/icons/arrow-up-dark.svg
arrow_icon_down: :/icons/arrow-down-dark.svg
arrow_icon_right: :/icons/arrow-right-dark.svg

uncheck_icon: :/icons/uncheck-dark.svg
check_icon: :/icons/check-dark.svg
limit_icon: :/icons/limit-dark.svg

tab_bg: #2F334D
tab_border_color: #414868
tab_selected_bg: #1A1B26

menu_bg: #1A1B26
menu_border: #414868

toolbar_bg: #181924
toolbar_border: #414868
toolbutton_hover_bg: #2F334D