# Dark theme: Solarized Dark
background: #002B36
foreground: #EEE8D5
faded_foreground: #93A1A1
highlight: #268BD2
selection_fg: #EEE8D5
selection_bg: #073642
border_radius: 8
icon_size: 16
eyedropper_icon: :/icons/eye-dropper-dark.svg

info_color: #2AA198
error_color: #DC322F
warning_color: #B58900

notification_width: 300
min_notification_height: 56
max_notification_height: 180

scrollbar_handle: #586E75
scrollbar_handle_hover: #657B83

button_size: 30

input_bg: #01212A
input_border: #073642
input_focus_border: #268BD2
combobox_bg: #073642
control_border: #586E75

combobox_hover_border: #2AA198
arrow_icon_up: :/icons/arrow-up-dark.svg
arrow_icon_down: :/icons/arrow-down-dark.svg
arrow_icon_right: :/icons/arrow-right-dark.svg

uncheck_icon: :/icons/uncheck-dark.svg
check_icon: :/icons/check-dark.svg
limit_icon: :/icons/limit-dark.svg

tab_bg: #073642
tab_border_color: #586E75
tab_selected_bg: #002B36

menu_bg: #002B36
menu_border: #586E75

toolbar_bg: #002730
toolbar_border: #586E75
toolbutton_hover_bg: #073642