# Dark theme
background: #2b2b2b
foreground: #e0e0e0
faded_foreground: #afafaf
highlight: #4a6ea9
selection_fg: #ffffff
selection_bg: #3d6fb4
border_radius: 8
icon_size: 16
eyedropper_icon: :/icons/eye-dropper-dark.svg

# General Colors
info_color: #4aa3ff
error_color: #ff5c5c
warning_color: #f2c94c

# Notification
notification_width: 360
min_notification_height: 56
max_notification_height: 180
notification_left_margin: 16
notification_top_margin: 16
notification_between_margin: 10

# Scroll bar
scrollbar_handle: #555555
scrollbar_handle_hover: #666666

# Button
button_size: 30

# General input
input_bg: #1f1f1f
input_border: #444444
input_focus_border: #638ecb
combobox_bg: #3c3f41
control_border: #555555

# Combo box
combobox_hover_border: #6b90c6
arrow_icon_up: :/icons/arrow-up-dark.svg
arrow_icon_down: :/icons/arrow-down-dark.svg
arrow_icon_right: :/icons/arrow-right-dark.svg

# Checkbox
uncheck_icon: :/icons/uncheck-dark.svg
check_icon: :/icons/check-dark.svg
limit_icon: :/icons/limit-dark.svg

# Tabs
tab_bg: #3c3f41
tab_border_color: #444444
tab_selected_bg: #2f2f2f

# Menu
menu_bg: #2b2b2b
menu_border: #444444

# Toolbar
toolbar_bg: #2c2c2c
toolbar_border: #444444
toolbutton_hover_bg: #3c3c3c
